### ISSUE TITLE
The performance in your paper is not consistent with the original paper?

### ISSUE THREAD

**Issue by c-yn** [qylen/DefocusGAN#1]
Dear author, 

The accuracy in Table 1 is not consistent with the scores reported in the original paper, such as KPAC.

For example, LPIPS and SSIM of the combined scene are much lower than theirs.

**Comment by jucaizhai** [comment]
是这样的，我问了kpac的作者，他们使用的是matlab计算的psnr和ssim，而我们和大多数论文使用的是python库。matlab计算的结果高一些。python计算的结果低一点



---Original---
From: "Yuning ***@***.***&gt;
Date: Sat, Dec 17, 2022 21:15 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [qylen/DefocusGAN] The performance in your paper is not consistentwith the original paper? (Issue #1)




 
Dear author,
 
The accuracy in Table 1 is not consistent with the scores reported in the original paper, such as KPAC.
 
For example, LPIPS and SSIM of the combined scene are much lower than theirs.

**Comment by c-yn** [comment]
> 是这样的，我问了kpac的作者，他们使用的是matlab计算的psnr和ssim，而我们和大多数论文使用的是python库。matlab计算的结果高一些。python计算的结果低一点
> […](#)
> ---Original--- From: "Yuning ***@***.***&gt; Date: Sat, Dec 17, 2022 21:15 PM To: ***@***.***&gt;; Cc: ***@***.***&gt;; Subject: [qylen/DefocusGAN] The performance in your paper is not consistentwith the original paper? (Issue #1) Dear author, The accuracy in Table 1 is not consistent with the scores reported in the original paper, such as KPAC. For example, LPIPS and SSIM of the combined scene are much lower than theirs. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

感谢回复，那LPIPS呢？感觉你论文里的LPIPS普遍比别的论文里要低（效果好）很多。比如你去掉数据增广，重新训练的IFAN，比原论文的LPIPS还要好。以及DPDNet_single的LPIPS，和restormer里的结果也有很大出入。

**Comment by jucaizhai** [comment]
这个也是使用python库内的lpips计算的。



---Original---
From: "Yuning ***@***.***&gt;
Date: Sat, Dec 17, 2022 21:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [qylen/DefocusGAN] The performance in your paper is notconsistent with the original paper? (Issue #1)




  
是这样的，我问了kpac的作者，他们使用的是matlab计算的psnr和ssim，而我们和大多数论文使用的是python库。matlab计算的结果高一些。python计算的结果低一点
 …
 ---Original--- From: "Yuning @.&gt; Date: Sat, Dec 17, 2022 21:15 PM To: @.&gt;; Cc: @.&gt;; Subject: [qylen/DefocusGAN] The performance in your paper is not consistentwith the original paper? (Issue #1) Dear author, The accuracy in Table 1 is not consistent with the scores reported in the original paper, such as KPAC. For example, LPIPS and SSIM of the combined scene are much lower than theirs. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
感谢回复，那LPIPS呢？感觉你论文里的LPIPS普遍比别的论文里要低（效果好）很多。比如你去掉数据增广，重新训练的IFAN，比原论文的LPIPS还要好。以及DPDNet_single的LPIPS，和restormer里的结果也有很大出入。

**Comment by jucaizhai** [comment]
我们使用的lpips的计算应该是和mpdnet，bambnet使用的计算方式一致。因为我使用的计算结果和他们的一致



---Original---
From: "Yuning ***@***.***&gt;
Date: Sat, Dec 17, 2022 21:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [qylen/DefocusGAN] The performance in your paper is notconsistent with the original paper? (Issue #1)




  
是这样的，我问了kpac的作者，他们使用的是matlab计算的psnr和ssim，而我们和大多数论文使用的是python库。matlab计算的结果高一些。python计算的结果低一点
 …
 ---Original--- From: "Yuning @.&gt; Date: Sat, Dec 17, 2022 21:15 PM To: @.&gt;; Cc: @.&gt;; Subject: [qylen/DefocusGAN] The performance in your paper is not consistentwith the original paper? (Issue #1) Dear author, The accuracy in Table 1 is not consistent with the scores reported in the original paper, such as KPAC. For example, LPIPS and SSIM of the combined scene are much lower than theirs. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
感谢回复，那LPIPS呢？感觉你论文里的LPIPS普遍比别的论文里要低（效果好）很多。比如你去掉数据增广，重新训练的IFAN，比原论文的LPIPS还要好。以及DPDNet_single的LPIPS，和restormer里的结果也有很大出入。

**Comment by c-yn** [comment]
> lpips

是MDPNet(wacv'22)吗？不过他的论文好像没有给出LPIPS这个指标

**Comment by jucaizhai** [comment]
那应该是我记错了.我们用的是和bamb一样的



---Original---
From: "Yuning ***@***.***&gt;
Date: Sat, Dec 17, 2022 22:18 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [qylen/DefocusGAN] The performance in your paper is notconsistent with the original paper? (Issue #1)




  
lpips
  
是MDPNet(wacv'22)吗？不过他的论文好像没有给出LPIPS这个指标

**Comment by c-yn** [comment]
收到 感谢您的答疑
