### ISSUE TITLE
Fuzzy kernel visualization

### ISSUE THREAD

**Issue by excllent123** [qylen/DefocusGAN#2]
How can I reproduce the results of Figure 6 in your paper? Can you provide a sample code?

**Comment by jucaizhai** [comment]
Hello, I’m happy to answer your question. This is just for Figure 6.3.
Because blur kernel parameters are two-dimensional arrays, grayscale image. You can convert it to PIL or OPENCV format for reading. like  ‘image= Image.fromarray(blurkernel)’
Figure 6.1/6.2 , we directly extracted the image from the paper(RDPDNet-ICCV2021)

**Comment by excllent123** [comment]
According to my understanding, KernelEDNet obtains the defocus map, and GemorestructNet obtains the corresponding fuzzy kernel according to the defocus map. Still, the corresponding weights are not disclosed, so the fuzzy kernel result of Figure 6 cannot be obtained. If my understanding is correct, can you provide weights? My email: hunter_yht@qq.com
